server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: siparis-service
  datasource:
    url: ${SIPARIS_SERVICE_DB_URL:jdbc:postgresql://postgres:5432/getirfinans_sipariss}
    username: ${SIPARIS_SERVICE_DB_USER:getirfinans_app}
    password: ${SIPARIS_SERVICE_DB_PASSWORD:not-real}
  sql:
    init:
      mode: always

siparis:
  domain: siparis-api.getirfinans.com
  callbackBaseUrl: https://getir.com/odeme-prod/callback
  fraudCheckUrl: https://fraud.getirfinans.com/fraud/evaluate
  tahsilatGatewayUrl: https://odeme-prod.getirfinans.com/tahsilat/intent

logging:
  level:
    root: INFO

